apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: frontend
  name: frontend
  namespace: control-plane
spec:
  # Using subdomain will add apps.cluster.domain to the host name.
  # Example: subdomain frontend automatically receives the router 
  # subdomain apps.mycluster.com to have a full hostname frontend.apps.mycluster.com.
  subdomain: frontend
  port:
    targetPort: https
  tls:
    termination: passthrough
  to:
    kind: Service
    name: istio-ingressgateway
    weight: 100
  wildcardPolicy: None
