apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: backend
  namespace: {{ .Values.istio.backend.destination.namespace }}
spec:
  host: {{ .Values.istio.backend.destination.host }}
  trafficPolicy:
    tls:
      mode: {{ .Values.istio.backend.destination.traffic_policy.mode }}
