apiVersion: v2
name: vault
description: Helm chart to deploy Vault to an OpenShift Cluster
type: application
version: 0.0.7
appVersion: "1.0.0"
dependencies: 
  - name: vault
    version: v0.20.1
    repository: https://helm.releases.hashicorp.com
    condition: vault.enabled
    tags:
      - vault
  - name: vault-bootstrap
    version: 0.1.5
    condition: vault-bootstrap.enabled
    tags:
      - vault-bootstrap
